version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./dist/apps/web:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./localhost+3-key.pem:/etc/ssl/localhost+3-key.pem
      - ./localhost+3.pem:/etc/ssl/localhost+3.pem
    ports:
      - 443:443
      - 80:80
